CREATE TABLE IF NOT EXISTS dim_nations ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome_pais TEXT NOT NULL,
    continente TEXT NOT NULL
);


INSERT INTO dim_nations (nome_pais, continente) VALUES
('Afeganistão', 'Ásia'),
('África do Sul', 'África'),
('Albânia', 'Europa'),
('Alemanha', 'Europa'),
('Andorra', 'Europa'),
('Angola', 'África'),
('Antígua e Barbuda', 'América do Norte'),
('Arábia Saudita', 'Ásia'),
('Argélia', 'África'),
('Argentina', 'América do Sul'),
('Armênia', 'Ásia'),
('Austrália', 'Oceania'),
('Áustria', 'Europa'),
('Azerbaijão', 'Ásia'),
('Bahamas', 'América do Norte'),
('Bahrein', 'Ásia'),
('Bangladesh', 'Ásia'),
('Barbados', 'América do Norte'),
('Bélgica', 'Europa'),
('Belize', 'América do Norte'),
('Benim', 'África'),
('Bielorrússia', 'Europa'),
('Bolívia', 'América do Sul'),
('Bósnia e Herzegovina', 'Europa'),
('Botsuana', 'África'),
('Brasil', 'América do Sul'),
('Brunei', 'Ásia'),
('Bulgária', 'Europa'),
('Burkina Faso', 'África'),
('Burundi', 'África'),
('Butão', 'Ásia'),
('Cabo Verde', 'África'),
('Camarões', 'África'),
('Camboja', 'Ásia'),
('Canadá', 'América do Norte'),
('Catar', 'Ásia'),
('Cazaquistão', 'Ásia'),
('Chade', 'África'),
('Chile', 'América do Sul'),
('China', 'Ásia'),
('Chipre', 'Europa'),
('Colômbia', 'América do Sul'),
('Comores', 'África'),
('Congo', 'África'),
('Coreia do Norte', 'Ásia'),
('Coreia do Sul', 'Ásia'),
('Costa do Marfim', 'África'),
('Costa Rica', 'América do Norte'),
('Croácia', 'Europa'),
('Cuba', 'América do Norte'),
('Dinamarca', 'Europa'),
('Djibuti', 'África'),
('Dominica', 'América do Norte'),
('Egito', 'África'),
('El Salvador', 'América do Norte'),
('Emirados Árabes Unidos', 'Ásia'),
('Equador', 'América do Sul'),
('Eritreia', 'África'),
('Eslováquia', 'Europa'),
('Eslovênia', 'Europa'),
('Espanha', 'Europa'),
('Essuatíni', 'África'),
('Estados Unidos', 'América do Norte'),
('Estônia', 'Europa'),
('Etiópia', 'África'),
('Fiji', 'Oceania'),
('Filipinas', 'Ásia'),
('Finlândia', 'Europa'),
('França', 'Europa'),
('Gabão', 'África'),
('Gâmbia', 'África'),
('Gana', 'África'),
('Geórgia', 'Ásia'),
('Granada', 'América do Norte'),
('Grécia', 'Europa'),
('Guatemala', 'América do Norte'),
('Guiana', 'América do Sul'),
('Guiné', 'África'),
('Guiné-Bissau', 'África'),
('Guiné Equatorial', 'África'),
('Haiti', 'América do Norte'),
('Honduras', 'América do Norte'),
('Hungria', 'Europa'),
('Iêmen', 'Ásia'),
('Ilhas Marshall', 'Oceania'),
('Ilhas Salomão', 'Oceania'),
('Índia', 'Ásia'),
('Indonésia', 'Ásia'),
('Irã', 'Ásia'),
('Iraque', 'Ásia'),
('Irlanda', 'Europa'),
('Islândia', 'Europa'),
('Israel', 'Ásia'),
('Itália', 'Europa'),
('Jamaica', 'América do Norte'),
('Japão', 'Ásia'),
('Jordânia', 'Ásia'),
('Kiribati', 'Oceania'),
('Kosovo', 'Europa'),
('Kuwait', 'Ásia'),
('Laos', 'Ásia'),
('Lesoto', 'África'),
('Letônia', 'Europa'),
('Líbano', 'Ásia'),
('Libéria', 'África'),
('Líbia', 'África'),
('Liechtenstein', 'Europa'),
('Lituânia', 'Europa'),
('Luxemburgo', 'Europa'),
('Macedônia do Norte', 'Europa'),
('Madagascar', 'África'),
('Malásia', 'Ásia'),
('Malawi', 'África'),
('Maldivas', 'Ásia'),
('Mali', 'África'),
('Malta', 'Europa'),
('Marrocos', 'África'),
('Maurício', 'África'),
('Mauritânia', 'África'),
('México', 'América do Norte'),
('Mianmar', 'Ásia'),
('Micronésia', 'Oceania'),
('Moçambique', 'África'),
('Moldávia', 'Europa'),
('Mônaco', 'Europa'),
('Mongólia', 'Ásia'),
('Montenegro', 'Europa'),
('Namíbia', 'África'),
('Nauru', 'Oceania'),
('Nepal', 'Ásia'),
('Nicarágua', 'América do Norte'),
('Níger', 'África'),
('Nigéria', 'África'),
('Noruega', 'Europa'),
('Nova Zelândia', 'Oceania'),
('Omã', 'Ásia'),
('Países Baixos', 'Europa'),
('Palau', 'Oceania'),
('Palestina', 'Ásia'),
('Panamá', 'América do Norte'),
('Papua-Nova Guiné', 'Oceania'),
('Paquistão', 'Ásia'),
('Paraguai', 'América do Sul'),
('Peru', 'América do Sul'),
('Polônia', 'Europa'),
('Portugal', 'Europa'),
('Quênia', 'África'),
('Quirguistão', 'Ásia'),
('Reino Unido', 'Europa'),
('República Centro-Africana', 'África'),
('República Democrática do Congo', 'África'),
('República Dominicana', 'América do Norte'),
('República Tcheca', 'Europa'),
('Romênia', 'Europa'),
('Ruanda', 'África'),
('Rússia', 'Europa'),
('Samoa', 'Oceania'),
('San Marino', 'Europa'),
('Santa Lúcia', 'América do Norte'),
('São Cristóvão e Névis', 'América do Norte'),
('São Tomé e Príncipe', 'África'),
('São Vicente e Granadinas', 'América do Norte'),
('Senegal', 'África'),
('Serra Leoa', 'África'),
('Sérvia', 'Europa'),
('Seychelles', 'África'),
('Singapura', 'Ásia'),
('Síria', 'Ásia'),
('Somália', 'África'),
('Sri Lanka', 'Ásia'),
('Sudão', 'África'),
('Sudão do Sul', 'África'),
('Suécia', 'Europa'),
('Suíça', 'Europa'),
('Suriname', 'América do Sul'),
('Tailândia', 'Ásia'),
('Tanzânia', 'África'),
('Tajiquistão', 'Ásia'),
('Timor-Leste', 'Ásia'),
('Togo', 'África'),
('Tonga', 'Oceania'),
('Trinidad e Tobago', 'América do Norte'),
('Tunísia', 'África'),
('Turcomenistão', 'Ásia'),
('Turquia', 'Europa'),
('Tuvalu', 'Oceania'),
('Ucrânia', 'Europa'),
('Uganda', 'África'),
('Uruguai', 'América do Sul'),
('Uzbequistão', 'Ásia'),
('Vanuatu', 'Oceania'),
('Vaticano', 'Europa'),
('Venezuela', 'América do Sul'),
('Vietnã', 'Ásia'),
('Zâmbia', 'África'),
('Zimbábue', 'África');
