drop table if exists dim_nations;

CREATE TABLE IF NOT EXISTS dim_nations ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome_pais TEXT NOT NULL,
    continente TEXT NOT NULL
);

INSERT INTO dim_nations (nome_pais, continente) VALUES
('Afeganistao', 'Asia'),
('Africa do Sul', 'Africa'),
('Albania', 'Europa'),
('Alemanha', 'Europa'),
('Andorra', 'Europa'),
('Angola', 'Africa'),
('Antigua e Barbuda', 'America do Norte'),
('Arabia Saudita', 'Asia'),
('Argelia', 'Africa'),
('Argentina', 'America do Sul'),
('Armenia', 'Asia'),
('Australia', 'Oceania'),
('Austria', 'Europa'),
('Azerbaijao', 'Asia'),
('Bahamas', 'America do Norte'),
('Bahrein', 'Asia'),
('Bangladesh', 'Asia'),
('Barbados', 'America do Norte'),
('Belgica', 'Europa'),
('Belize', 'America do Norte'),
('Benim', 'Africa'),
('Bielorrussia', 'Europa'),
('Bolivia', 'America do Sul'),
('Bosnia e Herzegovina', 'Europa'),
('Botsuana', 'Africa'),
('Brasil', 'America do Sul'),
('Brunei', 'Asia'),
('Bulgaria', 'Europa'),
('Burkina Faso', 'Africa'),
('Burundi', 'Africa'),
('Butao', 'Asia'),
('Cabo Verde', 'Africa'),
('Camaroes', 'Africa'),
('Camboja', 'Asia'),
('Canada', 'America do Norte'),
('Catar', 'Asia'),
('Cazaquistao', 'Asia'),
('Chade', 'Africa'),
('Chile', 'America do Sul'),
('China', 'Asia'),
('Chipre', 'Europa'),
('Colombia', 'America do Sul'),
('Comores', 'Africa'),
('Congo', 'Africa'),
('Coreia do Norte', 'Asia'),
('Coreia do Sul', 'Asia'),
('Costa do Marfim', 'Africa'),
('Costa Rica', 'America do Norte'),
('Croacia', 'Europa'),
('Cuba', 'America do Norte'),
('Curacao', 'America Central'),
('Dinamarca', 'Europa'),
('Djibuti', 'Africa'),
('Dominica', 'America do Norte'),
('Escocia', 'Europa'),
('Egito', 'Africa'),
('El Salvador', 'America do Norte'),
('Emirados Arabes Unidos', 'Asia'),
('Equador', 'America do Sul'),
('Eritreia', 'Africa'),
('Eslovaquia', 'Europa'),
('Eslovenia', 'Europa'),
('Espanha', 'Europa'),
('Essuatini', 'Africa'),
('Estados Unidos', 'America do Norte'),
('Estonia', 'Europa'),
('Etiopia', 'Africa'),
('Fiji', 'Oceania'),
('Filipinas', 'Asia'),
('Finlandia', 'Europa'),
('Franca', 'Europa'),
('Gabao', 'Africa'),
('Gambia', 'Africa'),
('Gana', 'Africa'),
('Georgia', 'Asia'),
('Granada', 'America do Norte'),
('Grecia', 'Europa'),
('Guatemala', 'America do Norte'),
('Guiana', 'America do Sul'),
('Guine', 'Africa'),
('Guine-Bissau', 'Africa'),
('Guine Equatorial', 'Africa'),
('Haiti', 'America Central'),
('Holanda', 'Europa'),
('Honduras', 'America Central'),
('Hungria', 'Europa'),
('Iemen', 'Asia'),
('Ilhas Marshall', 'Oceania'),
('Ilhas Salomao', 'Oceania'),
('India', 'Asia'),
('Indonesia', 'Asia'),
('Inglaterra', 'Europa'),
('Ira', 'Asia'),
('Iraque', 'Asia'),
('Irlanda', 'Europa'),
('Islandia', 'Europa'),
('Israel', 'Asia'),
('Italia', 'Europa'),
('Jamaica', 'America do Norte'),
('Japao', 'Asia'),
('Jordania', 'Asia'),
('Kiribati', 'Oceania'),
('Kosovo', 'Europa'),
('Kuwait', 'Asia'),
('Laos', 'Asia'),
('Lesoto', 'Africa'),
('Letonia', 'Europa'),
('Libano', 'Asia'),
('Liberia', 'Africa'),
('Libia', 'Africa'),
('Liechtenstein', 'Europa'),
('Lituania', 'Europa'),
('Luxemburgo', 'Europa'),
('Macedonia do Norte', 'Europa'),
('Madagascar', 'Africa'),
('Malasia', 'Asia'),
('Malawi', 'Africa'),
('Maldivas', 'Asia'),
('Mali', 'Africa'),
('Malta', 'Europa'),
('Marrocos', 'Africa'),
('Mauricio', 'Africa'),
('Mauritania', 'Africa'),
('Mexico', 'America do Norte'),
('Mianmar', 'Asia'),
('Micronesia', 'Oceania'),
('Mocambique', 'Africa'),
('Moldavia', 'Europa'),
('Monaco', 'Europa'),
('Mongolia', 'Asia'),
('Montenegro', 'Europa'),
('Namibia', 'Africa'),
('Nauru', 'Oceania'),
('Nepal', 'Asia'),
('Nicaragua', 'America do Norte'),
('Niger', 'Africa'),
('Nigeria', 'Africa'),
('Noruega', 'Europa'),
('Nova Zelandia', 'Oceania'),
('Oma', 'Asia'),
('Palau', 'Oceania'),
('Palestina', 'Asia'),
('Panama', 'America do Norte'),
('Papua-Nova Guine', 'Oceania'),
('Paquistao', 'Asia'),
('Paraguai', 'America do Sul'),
('Peru', 'America do Sul'),
('Polonia', 'Europa'),
('Portugal', 'Europa'),
('Quenia', 'Africa'),
('Quirguistao', 'Asia'),
('Reino Unido', 'Europa'),
('Republica Centro-Africana', 'Africa'),
('Republica Democratica do Congo', 'Africa'),
('Republica Dominicana', 'America do Norte'),
('Republica Tcheca', 'Europa'),
('Romenia', 'Europa'),
('Ruanda', 'Africa'),
('Russia', 'Europa'),
('Samoa', 'Oceania'),
('San Marino', 'Europa'),
('Santa Lucia', 'America do Norte'),
('Sao Cristovao e Nevis', 'America do Norte'),
('Sao Tome e Principe', 'Africa'),
('Sao Vicente e Granadinas', 'America do Norte'),
('Senegal', 'Africa'),
('Serra Leoa', 'Africa'),
('Servia', 'Europa'),
('Seychelles', 'Africa'),
('Singapura', 'Asia'),
('Siria', 'Asia'),
('Somalia', 'Africa'),
('Sri Lanka', 'Asia'),
('Sudao', 'Africa'),
('Sudao do Sul', 'Africa'),
('Suecia', 'Europa'),
('Suica', 'Europa'),
('Suriname', 'America do Sul'),
('Tailandia', 'Asia'),
('Tanzania', 'Africa'),
('Tajiquistao', 'Asia'),
('Timor-Leste', 'Asia'),
('Togo', 'Africa'),
('Tonga', 'Oceania'),
('Trinidad e Tobago', 'America do Norte'),
('Tunisia', 'Africa'),
('Turcomenistao', 'Asia'),
('Turquia', 'Europa'),
('Tuvalu', 'Oceania'),
('Ucrania', 'Europa'),
('Uganda', 'Africa'),
('Uruguai', 'America do Sul'),
('Uzbequistao', 'Asia'),
('Vanuatu', 'Oceania'),
('Vaticano', 'Europa'),
('Venezuela', 'America do Sul'),
('Vietna', 'Asia'),
('Zambia', 'Africa'),
('Zimbabue', 'Africa'),
('Generico 1', 'Desconecido'),
('Generico 2', 'Desconecido'),
('Generico 3', 'Desconecido'),
('Generico 4', 'Desconecido'),
('Generico 5', 'Desconecido'),
('Generico 6', 'Desconecido');